### ISSUE TITLE
SEEKING MAINTAINER!

### ISSUE THREAD

**Issue by sw-yx** [babel-blade/babel-blade#23]
i am no longer working on this - if you like the idea and want to take over the project, be my guest!

**Comment by ForsakenHarmony** [comment]
Definitely an interesting project, would be interested, but haven't looked into what needs to be done yet

**Comment by sw-yx** [comment]
sure, let me know

**Comment by CodyBrouwers** [comment]
Hey @sw-yx I would also be interested! I have a bunch of ideas that I’d like to try

**Comment by sw-yx** [comment]
transfering!

**Comment by sw-yx** [comment]
@CodyBrouwers  Do you mind deleting your fork? i cant transfer until you do 
![image](https://user-images.githubusercontent.com/6764957/68648101-63abc200-04d4-11ea-8292-2ab94d64a496.png)

**Comment by CodyBrouwers** [comment]
@sw-yx Yep sure, done! Also my NPM username is codybrouwers

@ForsakenHarmony, are you still interested in working on the project, I'd love to work together if you're up for it!

**Comment by ForsakenHarmony** [comment]
We could make a github org

**Comment by ForsakenHarmony** [comment]
https://github.com/babel-blade

@sw-yx you've been invited as well

**Comment by sw-yx** [comment]
hi! sorry for being MIA. transfering now

**Comment by sw-yx** [comment]
added both of you as admins!

**Comment by ForsakenHarmony** [comment]
Thanks
